# Generated by Django 6.0 on 2025-12-12 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_codigo_confirmacao_usuario_is_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_confirmacao',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
